Sunbird-Lern/lms-service

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/LearnerStateUpdateActor.java

fix for SB-14226 with status 1 and progress value.
error detail:
com.datastax.driver.core.exceptions.InvalidQueryException: Expected 4 or 0 byte int (1)

fix for progress cassandra batch insert error

---

.gitmodules

@maheshkumargangula Please review

Submodule version change to release-2.4.0

---

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/LearnerStateActor.java

fix for 
java.lang.NullPointerException\n\tat org.sunbird.learner.actors.LearnerStateActor.calculateProgressForUserCourses(LearnerStateActor.java:353)

Course search npe fix

---

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/LearnerStateUpdateActor.java

@maheshkumargangula Please review

Content State Update API changes to make contents list as optional

---

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/LearnerStateUpdateActor.java

@PradyumnaNagendra Please review

Issue #SB-14495 feat: Response fix after making contents list as optional

---

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/LearnerStateUpdateActor.java

@PradyumnaNagendra Please review

Issue #SB-14495 feat: Add batchId validation after making contents list as optional

---

actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/actors/certificate/CertificateActorTest.java
actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/actors/coursebatch/CourseEnrollmentActorTest.java

@PradyumnaNagendra Please review

Ignore test cases

---

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actor/operations/CourseActorOperations.java
actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/certificate/dao/CertificateDao.java
actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/certificate/dao/impl/CertificateDaoImpl.java
actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/certificate/service/CertificateActor.java
service/app/controllers/BaseController.java
service/app/controllers/certificate/CertificateController.java
service/app/controllers/certificate/CertificateRequestValidator.java
service/app/modules/ErrorHandler.java
service/conf/routes
service/pom.xml
service/test/controllers/LearnerControllerTest.java
service/test/controllers/cache/CacheControllerTest.java
service/test/controllers/certificate/CertificateControllerTest.java

test cases changes and adding rules for validating test cases at build time

Release 2.5.0

---

course-mw/course-actors-common/src/main/java/org/sunbird/learner/util/ContentUtil.java
course-mw/course-actors-common/src/test/java/org/sunbird/learner/util/ContentUtilTest.java
course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActor.java
course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseEnrollmentActor.java
course-mw/course-actors/src/test/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActorTest.java

Updating coursebatch - change search to read call for course validation

---

course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseEnrollmentActor.java

SH-265: Ignoring validation of userToken and userid passed in the request

---

course-mw/course-actors/src/main/java/org/sunbird/learner/actors/LearnerStateUpdateActor.java

Group data by userId and process.

Content State Update API - Refactoring - For Authorization and Mobile support - Part 2

---

course-mw/enrolment-actor/src/main/scala/org/sunbird/group/GroupAggregatesActor.scala
course-mw/enrolment-actor/src/main/scala/org/sunbird/group/GroupAggregatesUtil.scala
service/app/util/RequestInterceptor.java

SC-1812: Group activity aggregates API - adding logs

---

course-mw/enrolment-actor/src/main/scala/org/sunbird/group/GroupAggregatesUtil.scala

SC-1812: Group activity aggregates API - adding log

---

.circleci/config.yml
course-mw/enrolment-actor/src/main/scala/org/sunbird/enrolments/CourseEnrolmentActor.scala
course-mw/enrolment-actor/src/test/scala/org/sunbird/enrolments/CourseEnrolmentTest.scala

Fixed for multiple batch enrolments for the same course

Issue #SB-21980 fix: enrolment list API fix

---

course-mw/enrolment-actor/src/main/scala/org/sunbird/aggregate/CollectionSummaryAggregate.scala

…anularity for the specific batch & courseid.

 Collection summary api granularity query issue fix

---

course-mw/course-actors-common/src/main/java/org/sunbird/learner/util/ContentUtil.java
course-mw/course-actors-common/src/test/java/org/sunbird/learner/util/ContentUtilTest.java
course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActor.java
course-mw/course-actors/src/test/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActorTest.java
course-mw/course-actors/src/test/java/org/sunbird/learner/actors/coursemanagement/CourseBatchManagementActorTest.java

SB-24096 fix: CourseBatch status issue

---

course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActor.java

Issue #SB-24096 fix: CourseBatch status issue

---

course-mw/course-actors-common/src/main/java/org/sunbird/learner/util/ContentUtil.java
course-mw/course-actors-common/src/test/java/org/sunbird/learner/util/ContentUtilTest.java
course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActor.java
course-mw/course-actors/src/test/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActorTest.java
course-mw/course-actors/src/test/java/org/sunbird/learner/actors/coursemanagement/CourseBatchManagementActorTest.java
course-mw/enrolment-actor/src/main/scala/org/sunbird/group/GroupAggregatesActor.scala

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SC-2218" title="SC-2218" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SC-2218</a>  Groups to report activity scores in addition to progress
</td></table>
<br />
* Software versions: Java-11, play2-2.7.2, …

SC-2218: Scores in group aggregates

---

course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/PageManagementActor.java
course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/coursebatch/dao/impl/UserCoursesDaoImpl.java
course-mw/enrolment-actor/src/main/scala/org/sunbird/enrolments/ContentConsumptionActor.scala
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-22541" title="SB-22541" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-22541</a>  MC - Certificates enhancements
</td></table>
<br /> …

SB-22541 : Page changes for created date

---

course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/PageManagementActor.java
course-mw/enrolment-actor/src/main/scala/org/sunbird/enrolments/ContentConsumptionActor.scala
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/util/JsonUtil.java

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-22541" title="SB-22541" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-22541</a>  MC - Certificates enhancements
</td></table>
<br /> …

SB-22541 : Fix for content state timezone

---

course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActor.java

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-22541" title="SB-22541" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-22541</a>  MC - Certificates enhancements
</td></table>
<br /> …

SB-22541 : oldEndDate and enrolmentEndDate added in 24 hrs format

---

course-mw/enrolment-actor/src/main/scala/org/sunbird/aggregate/CollectionSummaryAggregate.scala

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24505" title="SB-24505" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10303&avatarType=issuetype" />SB-24505</a>  Enrolment count not coming up in course dashboard
</td></table>
<br />
* Software versions: Java-11, play2-2.7.2, …

SB-24505 - Collection summary agg api issue fix 

---

course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActor.java
course-mw/course-actors/src/test/java/org/sunbird/learner/actors/coursemanagement/CourseBatchManagementActorTest.java

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24553" title="SB-24553" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-24553</a>  Backend: Capability to edit batch end date for expired batches
</td></table>
<br />
The change is to extend the endDate of expired batches

SB-24553: Extend end date for expired batches

---

course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/cassandratablecolumn.properties

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24659" title="SB-24659" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24659</a>  When the creator updates the batch details, the added certificate gets removed.
</td></table>
<br />
* Software …

Issue #SB-24659 fix: Fixed missing cert_templates in ES on batchUpdate

---

course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActor.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/cassandratablecolumn.properties

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24659" title="SB-24659" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24659</a>  When the creator updates the batch details, the added certificate gets removed.
</td></table>
<br />
* Software …

SB-24659 fix: Fixed missing cert_templates in ES on batchUpdate

---

course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/certificate/service/CourseBatchCertificateActor.java
course-mw/course-actors-common/src/main/java/org/sunbird/learner/constants/CourseJsonKey.java
course-mw/course-actors-common/src/main/java/org/sunbird/learner/util/CourseBatchUtil.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/LoggerUtil.java
service/conf/logback.xml

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24659" title="SB-24659" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24659</a>  When the creator updates the batch details, the added certificate gets removed.
</td></table>
<br />
* Software …

#SB-24659 fix: Fixed missing cert_templates in ES on batchUpdate

---

course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/certificate/service/CourseBatchCertificateActor.java
course-mw/course-actors-common/src/main/java/org/sunbird/learner/constants/CourseJsonKey.java
course-mw/course-actors-common/src/main/java/org/sunbird/learner/util/CourseBatchUtil.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/LoggerUtil.java
service/conf/logback.xml

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24659" title="SB-24659" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24659</a>  When the creator updates the batch details, the added certificate gets removed.
</td></table>
<br />
* Software …

SB-24659 - Merge releases-3.9.0 to release 4.0.0

---

course-mw/course-actors-common/src/main/java/org/sunbird/actor/base/BaseActor.java
course-mw/enrolment-actor/src/main/scala/org/sunbird/enrolments/ContentConsumptionActor.scala
course-mw/enrolment-actor/src/test/scala/org/sunbird/enrolments/CourseConsumptionActorTest.scala
course-mw/sunbird-util/sunbird-cassandra-utils/src/main/java/org/sunbird/cassandraimpl/CassandraOperationImpl.java
course-mw/sunbird-util/sunbird-cassandra-utils/src/main/java/org/sunbird/common/CassandraUtil.java
course-mw/sunbird-util/sunbird-platform-core/actor-core/src/main/java/org/sunbird/actor/core/BaseActor.java
service/app/controllers/BaseController.java
service/app/controllers/healthmanager/HealthController.java

<table>
<td>
</td></table>
<br />
* …

SB-25890 - Refactoring to set the submitted assessment status as completed

---

service/app/controllers/LearnerController.java
service/conf/application.conf

<table>
<td>
</td></table>
<br />
* …

SB-25890 - Logging ContentStateUpdate API request and response status

---

course-mw/sunbird-util/sunbird-platform-core/auth-verifier/src/main/java/org/sunbird/auth/verifier/AccessTokenValidator.java
course-mw/sunbird-util/sunbird-platform-core/auth-verifier/src/test/java/org/sunbird/auth/verifier/AccessTokenValidatorTest.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
service/app/controllers/LearnerController.java
service/app/modules/OnRequestHandler.java
service/app/util/Attrs.java

<table>
<td>
</td></table>
<br />
* …

Issue #SB-25890 feat: logging update

---

service/app/controllers/LearnerController.java

<table>
<td>
</td></table>
<br />
* …

SB-25890 feat: updated logging to have requestedBy, requestedFor, request and response code with errors.

---

service/app/modules/ActorStartModule.java
service/conf/application.conf

<table>
<td>
</td></table>
<br />
This reverts commit 83d2f5a599facf7acdee2e37dade1b812ed92312, reversing
changes made to 5f09f5b232106614041abf7b2c34754eb7e51b27.
Please describe the tests that you ran to verify your changes in the below checkboxes. …

Revert "Merge pull request #383 from project-sunbird/SB-25890"

---

course-mw/course-actors-common/src/main/java/org/sunbird/actor/base/BaseActor.java
course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/search/SearchHandlerActor.java
course-mw/course-actors-common/src/main/java/org/sunbird/learner/util/CourseBatchUtil.java
course-mw/enrolment-actor/src/main/scala/org/sunbird/enrolments/ContentConsumptionActor.scala
course-mw/enrolment-actor/src/test/scala/org/sunbird/enrolments/CourseConsumptionActorTest.scala
course-mw/sunbird-util/sunbird-cassandra-utils/src/main/java/org/sunbird/cassandraimpl/CassandraOperationImpl.java
course-mw/sunbird-util/sunbird-cassandra-utils/src/main/java/org/sunbird/common/CassandraUtil.java
course-mw/sunbird-util/sunbird-platform-core/actor-core/src/main/java/org/sunbird/actor/core/BaseActor.java
course-mw/sunbird-util/sunbird-platform-core/auth-verifier/src/main/java/org/sunbird/auth/verifier/AccessTokenValidator.java
course-mw/sunbird-util/sunbird-platform-core/auth-verifier/src/test/java/org/sunbird/auth/verifier/AccessTokenValidatorTest.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
service/app/controllers/BaseController.java
service/app/controllers/LearnerController.java
service/app/controllers/healthmanager/HealthController.java
service/app/modules/ActorStartModule.java
service/app/modules/OnRequestHandler.java
service/app/util/Attrs.java
service/conf/application.conf

Merge release-4.1.0 to release 4.2.0

---

course-mw/enrolment-actor/src/main/scala/org/sunbird/enrolments/CourseEnrolmentActor.scala
course-mw/enrolment-actor/src/test/scala/org/sunbird/enrolments/CourseEnrolmentTest.scala
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/BaseRequestValidator.java
service/app/controllers/BaseController.java
service/app/controllers/LearnerController.java
service/app/controllers/courseenrollment/CourseEnrollmentController.java
service/conf/routes
service/test/controllers/LearnerControllerTest.java
service/test/controllers/courseenrollment/CourseEnrollmentControllerTest.java

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-27532" title="SB-27532" target="_blank"><img alt="Enhancement" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10311&avatarType=issuetype" />SB-27532</a>  Validating authToken for enrol API
</td></table>
<br /> …

SB-27532 feat: Added authToken verification for enrolment APIs

---

service/app/controllers/courseenrollment/CourseEnrollmentController.java

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-27532" title="SB-27532" target="_blank"><img alt="Enhancement" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10311&avatarType=issuetype" />SB-27532</a>  Validating authToken for enrol API
</td></table>
<br /> …

SB-27532 feat: Added authToken verification for enrolList API

---

service/app/controllers/LearnerController.java
service/app/controllers/courseenrollment/CourseEnrollmentController.java

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-27632" title="SB-27632" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-27632</a>  Mobile app: Courses enrolled by LUA user get displayed to MUA user also
</td></table>
<br />
* Software versions: …

SB-27632 fix: Fixed managed user enrol API issue

---

course-mw/enrolment-actor/src/test/scala/org/sunbird/enrolments/CourseEnrolmentTest.scala
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/BaseRequestValidator.java
service/app/controllers/BaseController.java
service/app/controllers/LearnerController.java
service/app/controllers/courseenrollment/CourseEnrollmentController.java
service/conf/routes
service/test/controllers/LearnerControllerTest.java
service/test/controllers/courseenrollment/CourseEnrollmentControllerTest.java

Merge release-4.4.0 to release 4.5.0

---

service/app/controllers/LearnerController.java
service/conf/routes

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-27532" title="SB-27532" target="_blank"><img alt="Enhancement" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10311&avatarType=issuetype" />SB-27532</a>  Validating authToken for enrol API
</td></table>
<br /> …

Issue #SB-27532 fix: Added private API for content state read

---

course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActor.java
course-mw/course-actors/src/test/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActorTest.java
course-mw/course-actors/src/test/java/org/sunbird/learner/actors/coursemanagement/CourseBatchManagementActorTest.java

Issue #000 fix: Restrict batch creation or update without leafNodes

---

course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActor.java
course-mw/course-actors/src/test/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActorTest.java
course-mw/course-actors/src/test/java/org/sunbird/learner/actors/coursemanagement/CourseBatchManagementActorTest.java

Merge release-4.5.0 to Release 4.6.0

---

course-mw/enrolment-actor/src/main/scala/org/sunbird/enrolments/CourseEnrolmentActor.scala
course-mw/enrolment-actor/src/main/scala/org/sunbird/group/GroupAggregatesActor.scala
course-mw/enrolment-actor/src/test/scala/org/sunbird/group/GroupAggregatesActorTest.scala

1. Check for Aggr field for null
2. Check for lastupdate date null value for missing parameters in agg_last_updated field, while max operation

SB-29398 : Fixed Group Aggregates

---

course-mw/enrolment-actor/src/main/scala/org/sunbird/enrolments/CourseEnrolmentActor.scala
course-mw/enrolment-actor/src/test/scala/org/sunbird/enrolments/CourseEnrolmentTest.scala
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties

<table>
<td>
</td></table>
<br /> …

Issue #SB-28497 feat: filter the latest 1000 enrolled course in list api

---

course-mw/enrolment-actor/src/main/scala/org/sunbird/enrolments/CourseEnrolmentActor.scala

<table>
<td>
</td></table>
<br /> …

Issue #SB-28497 feat:fixed sorting issue

---

course-mw/enrolment-actor/src/main/scala/org/sunbird/enrolments/CourseEnrolmentActor.scala

<table>
<td>
</td></table>
<br /> …

Issue #SB-28497 feat:fixed user unable to join course issue

---

course-mw/enrolment-actor/src/main/scala/org/sunbird/enrolments/CourseEnrolmentActor.scala

<table>
<td>
</td></table>
<br /> …

Issue #SB-28497 | added info and error logs

---

course-mw/enrolment-actor/src/main/scala/org/sunbird/enrolments/CourseEnrolmentActor.scala

<table>
<td>
</td></table>
<br /> …

Issue #SB-28497 | added error and info logs 

---

service/app/controllers/certificate/CertificateRequestValidator.java

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29072" title="SB-29072" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-29072</a>  [Add certificate template API] If add certificate template API is having valid values in all the Certificate Signatorylist attributes then, template is not get added to course certificate and 400 Bad request status response is shown
</td></table>
<br />
Please describe the tests that you ran to verify your changes in the below …

Issue #SB-29072 | certificate template API fix on validation

---

Jenkinsfile
course-mw/sunbird-util/sunbird-cassandra-utils/src/test/java/org/sunbird/cassandraimpl/CassandraDACImplTest.java

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29648" title="SB-29648" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-29648</a>  Enabling unit tests in course service
</td></table>
<br />
* Software versions: Java-11, play2-2.7.2, …

Issue #SB-29648 mvn build tests

---

.circleci/config.yml
course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/qrcodedownload/QRCodeDownloadManagementActor.java
course-mw/course-actors-common/src/test/java/org/sunbird/learner/util/JsonUtilTest.java
course-mw/enrolment-actor/src/test/scala/org/sunbird/enrolments/CourseEnrolmentTest.scala
course-mw/sunbird-util/sunbird-platform-core/common-util/pom.xml
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/aws/AwsCloudService.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/aws/AwsConnectionManager.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/aws/AwsFileUtility.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/azure/AzureCloudService.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/cloud/CloudService.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/cloud/CloudServiceFactory.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/cloud/CloudUtils.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/gcloud/GcpCloudConnectionManager.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/gcloud/GcpCloudService.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/gcloud/GcpFileUtility.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/util/CloudStorageUtil.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties
course-mw/sunbird-util/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/models/util/aws/AwsServiceFactoryTest.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/models/util/azure/AzureServiceFactoryTest.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/models/util/gcloud/GcpCloudServiceFactoryTest.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/util/CloudStorageUtilTest.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/util/CloudUtilsTest.java
course-mw/textbook-actors/src/main/java/org/sunbird/content/util/ContentCloudStore.java
course-mw/textbook-actors/src/test/java/org/sunbird/learner/actors/textbook/TextbookTocActorTest.java

Issue #LR-104 feat:CSP related change for sunbird-course-service

---

course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java

Issue #LR-110 feat:added env for csp

---

course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties

Issue #SB-30930 feat:updated pdata version

---

course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/aws/AwsConnectionManager.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/aws/AwsFileUtility.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/gcloud/GcpCloudConnectionManager.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/gcloud/GcpFileUtility.java

Issue #LR-110 feat: fixed csp connection issue

---

course-mw/sunbird-util/sunbird-cassandra-utils/src/main/java/org/sunbird/cassandraimpl/CassandraOperationImpl.java
course-mw/sunbird-util/sunbird-cassandra-utils/src/main/java/org/sunbird/helper/CassandraConnectionManagerImpl.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/cassandra.config.properties

Cassandra consistency and ifExists removed

---

course-mw/sunbird-util/sunbird-platform-core/common-util/pom.xml

Issue #LR-110 feat:upgraded cloud sdk

---

.circleci/config.yml
course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/qrcodedownload/QRCodeDownloadManagementActor.java
course-mw/course-actors-common/src/test/java/org/sunbird/learner/util/JsonUtilTest.java
course-mw/enrolment-actor/src/test/scala/org/sunbird/enrolments/CourseEnrolmentTest.scala
course-mw/sunbird-util/sunbird-cassandra-utils/src/main/java/org/sunbird/cassandraimpl/CassandraOperationImpl.java
course-mw/sunbird-util/sunbird-cassandra-utils/src/main/java/org/sunbird/common/Constants.java
course-mw/sunbird-util/sunbird-cassandra-utils/src/main/java/org/sunbird/helper/CassandraConnectionManagerImpl.java
course-mw/sunbird-util/sunbird-platform-core/common-util/pom.xml
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/aws/AwsCloudService.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/aws/AwsConnectionManager.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/aws/AwsFileUtility.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/azure/AzureCloudService.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/cloud/CloudService.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/cloud/CloudServiceFactory.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/cloud/CloudUtils.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/gcloud/GcpCloudConnectionManager.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/gcloud/GcpCloudService.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/gcloud/GcpFileUtility.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/util/CloudStorageUtil.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/cassandra.config.properties
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties
course-mw/sunbird-util/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/models/util/aws/AwsServiceFactoryTest.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/models/util/azure/AzureServiceFactoryTest.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/models/util/gcloud/GcpCloudServiceFactoryTest.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/util/CloudStorageUtilTest.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/util/CloudUtilsTest.java
course-mw/textbook-actors/src/main/java/org/sunbird/content/util/ContentCloudStore.java
course-mw/textbook-actors/src/test/java/org/sunbird/content/util/TextBookTocUtilTest.java
course-mw/textbook-actors/src/test/java/org/sunbird/learner/actors/textbook/TextbookTocActorTest.java

Release 5.0.0

---

course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties
service/app/filters/ResponseFilter.scala
service/conf/application.conf

LR-265 Resolving the cloud url /CName

---

course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/certificate/service/CourseBatchCertificateActor.java
course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/qrcodedownload/QRCodeDownloadManagementActor.java
course-mw/course-actors-common/src/main/java/org/sunbird/learner/util/CourseBatchUtil.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/util/CloudStorageUtil.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties
course-mw/sunbird-util/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/util/CloudStorageUtilTest.java
course-mw/textbook-actors/src/main/java/org/sunbird/learner/actors/textbook/TextbookTocActor.java

LR-265 csp template variable changes

---

course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties

LR-262 variable change

---

course-mw/sunbird-util/sunbird-platform-core/common-util/pom.xml
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/util/CloudStorageUtil.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/util/CloudStorageUtilTest.java

Gloud signed url support changes added

---

course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
service/app/modules/OnRequestHandler.java
service/app/util/RequestInterceptor.java
service/conf/application.conf
service/test/controllers/LearnerControllerTest.java
service/test/controllers/cache/CacheControllerTest.java
service/test/controllers/courseenrollment/CourseEnrollmentControllerTest.java
service/test/controllers/courseenrollment/CourseEnrollmentControllerTest2.java

LR-251 - BatchService-Identity manager should be optional for setup

---

course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties

ED-621:templateUrl placeholder value changed

---

course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/qrcodedownload/QRCodeDownloadManagementActor.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties

LR-278 - File URL is not having new cname changes fix

---

course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties

ED-621 changing telemetry version

---

course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActor.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/BaseRequestValidator.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/application.conf
service/conf/application.conf

LR-310 - adding extra scenarios for auth enabled

---

course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties

updating the telemetry version

---

scripts/lms-config.sh

Issue #0000 feat: Boot Camp setup

---

scripts/postman/Bootcamp-2023.postman_collection.json
scripts/postman/bootcamp-2023.postman_environment.json

Issue #LR-0000 feat: Adding the postman collection.

---

course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties

LR-329 - changes for telemetry version

---

.circleci/config.yml
course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/qrcodedownload/QRCodeDownloadManager.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties

Issue #LR-325 feat: Refactoring of SB Lern Batch Service - DialCode Dependency

---

.circleci/config.yml
course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/qrcodedownload/QRCodeDownloadManager.java

Issue #KN-889 fix: CSV file downloaded showing null for all QR code 

---

.gitignore
course-mw/sunbird-util/sunbird-notification/pom.xml
course-mw/sunbird-util/sunbird-platform-core/common-util/pom.xml
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/util/CloudStorageUtil.java
service/pom.xml

Issue #LR-627 merge: OCI CSP changes from release-5.0.2 to release-5.1.0

---

.gitignore
course-mw/sunbird-util/sunbird-notification/pom.xml
course-mw/sunbird-util/sunbird-platform-core/common-util/pom.xml
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/util/CloudStorageUtil.java
service/pom.xml

Issue #LR-627 merge: OCI CSP changes from release-5.0.2 to release-5.2.0

---

.gitignore
course-mw/sunbird-util/sunbird-notification/pom.xml
course-mw/sunbird-util/sunbird-platform-core/common-util/pom.xml
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/util/CloudStorageUtil.java
service/pom.xml

Issue #LR-627 merge: OCI CSP changes from release-5.0.2 to release-5.2.1

---

.gitignore
course-mw/sunbird-util/sunbird-platform-core/common-util/pom.xml
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/util/CloudStorageUtil.java

Issue #LR-627 merge: OCI CSP changes from release-5.0.2 to release-5.3.1

---

course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties

Issue #KN-889 fix: CSV file downloaded showing null for all QR code images

---

.circleci/config.yml
.gitignore
Dockerfile.Build
Jenkinsfile
auto_build_deploy
course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/qrcodedownload/QRCodeDownloadManager.java
course-mw/sunbird-util/sunbird-platform-core/common-util/pom.xml
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/ProjectUtil.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/util/CloudStorageUtil.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties
course-mw/sunbird-util/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/models/util/ProjectUtilTest.java
service/dependency-reduced-pom.xml

Issue #LR-627 merge: OCI CSP changes from release-5.0.2 to release-5.4.0

---

.circleci/config.yml
.gitignore
Dockerfile.Build
Jenkinsfile
api-tests/Collection/Lms_APIs Test.postman_collection.json
api-tests/Collection/Lms_APIs.postman_collection.json
api-tests/Collection/Lms_Environment.postman_environment.json
auto_build_deploy
course-mw/course-actors-common/src/main/java/org/sunbird/common/cacheloader/PageCacheLoaderService.java
course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/bulkupload/dao/impl/BulkUploadProcessDaoImpl.java
course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/qrcodedownload/QRCodeDownloadManager.java
course-mw/course-actors-common/src/main/java/org/sunbird/learner/util/DataCacheHandler.java
course-mw/course-actors-common/src/main/java/org/sunbird/learner/util/Util.java
course-mw/sunbird-util/cache-utils/src/main/scala/org/sunbird/cache/util/RedisCacheUtil.scala
course-mw/sunbird-util/sunbird-cache-utils/src/main/java/org/sunbird/redis/RedisConnectionManager.java
course-mw/sunbird-util/sunbird-cassandra-utils/src/test/java/org/sunbird/cassandraimpl/CassandraDACImplTest.java
course-mw/sunbird-util/sunbird-platform-core/common-util/pom.xml
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/ProjectUtil.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/TableNameUtil.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/url/EsConfigUtil.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/util/CloudStorageUtil.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties
course-mw/sunbird-util/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/models/util/ProjectUtilTest.java
service/dependency-reduced-pom.xml

Issue #LR-583 merge: release-5.4.0 to master

---

course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/resources/externalresource.properties

repo name changes from sunbird to sunbird_userorg_keyspace

---

.github/BUILD.md
.github/workflows/build.yml

This PR adds a GitHub Actions workflow to the `lms-service` repository.
**Build and Deploy** `build.yml`
Triggers when a Git tag is pushed.  
Builds the project, packages the artifact, builds a Docker image, and pushes it to GitHub Container Registry (GHCR).

SBCOSS-448: Sunbird LMS service  - create Github actions to publish docker image to GHCR

---

.github/COVERAGE.md
.github/workflows/pr_actions.yml

This PR adds a GitHub Actions workflow for PR code coverage and quality checks to the `lms-service` repository.
- **Triggers**: When a pull request is created against any branch.
- **Functionality**: 
- Builds the project
- Runs unit tests
- Generates a coverage report using JaCoCo
- Performs static code analysis with SonarQube
This workflow ensures that every proposed change is validated for code quality and coverage before merging.

SBCOSS-425: Sunbird LMS service - add the GitHub actions to run test cases and code quality checks when a PR raised

---

course-mw/sunbird-util/sunbird-es-utils/pom.xml

Downgrade the Elasticsearch client library version from 7.17.13 to 7.10.2 in the `sunbird-es-utils` module.
The downgrade is necessary to ensure compatibility with other system components that are not yet compatible with Elasticsearch version 7.17.13. The selected …

SBCOSS-412: Downgraded ES version from 7.17.13 to 7.10.2
